services:
  foundry:
    image: wernerwaage/node-foundryvtt:v13
    volumes:
      - E:\docker2025\wernerwaage-foundryvtt\data:/data
      - E:\docker2025\wernerwaage-foundryvtt\pkg:/pkg
    ports:
      - target: 30000
        published: 30000
        protocol: tcp